// <auto-generated />
using System;
using CompraProgramada.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompraProgramada.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompraProgramada.Domain.Entities.CestaRecomendacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CestasRecomendadas");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasDatabaseName("UX_Cliente_CPF");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ContaGrafica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("NumeroConta")
                        .IsUnique()
                        .HasDatabaseName("UX_ContaGrafica_Numero");

                    b.ToTable("ContasGraficas");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Cotacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataPregao")
                        .HasColumnType("DATE");

                    b.Property<decimal>("PrecoAbertura")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("PrecoFechamento")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("PrecoMaximo")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("PrecoMinimo")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Ticker");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "DataPregao")
                        .IsUnique()
                        .HasDatabaseName("UX_Cotacao_TickerData");

                    b.ToTable("Cotacoes");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Custodia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContaGraficaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ContaGraficaId1")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("DATETIME");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Ticker");

                    b.HasKey("Id");

                    b.HasIndex("ContaGraficaId1");

                    b.HasIndex("ContaGraficaId", "Ticker")
                        .IsUnique()
                        .HasDatabaseName("UX_Custodia_ContaTicket");

                    b.ToTable("Custodias");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Distribuicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CustodiaFilhoteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataDistribuicao")
                        .HasColumnType("DATETIME");

                    b.Property<long>("OrdemCompraId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CustodiaFilhoteId");

                    b.HasIndex("OrdemCompraId", "DataDistribuicao")
                        .HasDatabaseName("IX_Distribuicao_OrdemData");

                    b.ToTable("Distribuicoes");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.EventoIR", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("PublicadoKafka")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("ValorBase")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("ValorIR")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "DataEvento")
                        .HasDatabaseName("IX_EventoIR_ClienteData");

                    b.ToTable("EventosIR");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.OrdemCompra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContaMasterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("DATETIME");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Ticker");

                    b.Property<string>("TipoMercado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ContaMasterId", "DataExecucao")
                        .HasDatabaseName("IX_OrdemCompra_ContaMasterData");

                    b.ToTable("OrdensCompra");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Rebalanceamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataRebalanceamento")
                        .HasColumnType("DATETIME");

                    b.Property<string>("TickerComprado")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TickerComprado");

                    b.Property<string>("TickerVendido")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TickerVendido");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "DataRebalanceamento")
                        .HasDatabaseName("IX_Rebalanceamento_ClienteData");

                    b.ToTable("Rebalanceamentos");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.CestaRecomendacao", b =>
                {
                    b.OwnsMany("CompraProgramada.Domain.Entities.ItemCesta", "Itens", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<long>("CestaId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Percentual")
                                .HasColumnType("DECIMAL(5,2)")
                                .HasColumnName("Percentual");

                            b1.Property<string>("Ticker")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("Ticker");

                            b1.HasKey("Id");

                            b1.HasIndex("CestaId");

                            b1.ToTable("CestaRecomendacaoItens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CestaId");
                        });

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ContaGrafica", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.Cliente", "Cliente")
                        .WithOne()
                        .HasForeignKey("CompraProgramada.Domain.Entities.ContaGrafica", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Custodia", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.ContaGrafica", null)
                        .WithMany()
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompraProgramada.Domain.Entities.ContaGrafica", "ContaGrafica")
                        .WithMany()
                        .HasForeignKey("ContaGraficaId1");

                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Distribuicao", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.Custodia", null)
                        .WithMany()
                        .HasForeignKey("CustodiaFilhoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompraProgramada.Domain.Entities.OrdemCompra", null)
                        .WithMany()
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
